version: "3.2"

services:
  db:
    image: mariadb:10
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=drupal
      - MARIADB_USER=drupal
      - MARIADB_PASSWORD=drupal
    expose:
      - 3306

  drupal:
    build: ./
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://drupal:drupal@db/drupal
    volumes:
      - type: bind
        source: ./src
        target: /src
        consistency: delegated
      - /app/node_modules
    ports:
      - 8080:80

volumes:
  pgdata: